name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - name: make VaST
      run: make
    - name: test VaST
      run: util/examples/test_vast.sh
